[project]
name = "auto-diary"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "flet[all]==0.28.3",
    "mss>=10.1.0",
    "openai>=2.6.0",
    "pillow>=12.0.0",
    "python-dotenv>=1.1.1",
]
